### ISSUE TITLE
error with autoit info

### ISSUE THREAD

**Issue by Gishi1** [loganch/AutoIt-VSCode#12]
hello i have a fresh install with autoit and SciTE4AutoIt3 installed and im getting an error: command 'extension.launchInfo' not found.

**Comment by loganch** [comment]
Do the other commands work?

**Comment by Gishi1** [comment]
i tried bringing up the help and got Error: command 'extension.launchHelp' not found so it seems none work.

**Comment by loganch** [comment]
Do you happen to be running a 32-bit version of Windows?

**Comment by Gishi1** [comment]
no windows 10 x64

**Comment by Gishi1** [comment]
same problem on my desktop and laptop.

**Comment by Gishi1** [comment]
okay i found what it was.... turns out you have to have an au3 open to use any of the commands... came to my attention as i was looking threw your code isAutoIt()... should only be used when its needed not all the time.

**Comment by Gishi1** [comment]
or at least add a prompt when its false to let the user know they need a file open.

**Comment by loganch** [comment]
Oh, right, I noticed that as an issue earlier when I started on the extension. Basically, the commands are added to VS Code when the extension is installed, but none of the code behind them is available until you open a .au3 file. 

Thanks for bringing this back to my attention. I'll take a look into what I can do about it.

**Comment by Gishi1** [comment]
well i hope there's a work around for it.

**Comment by loganch** [comment]
Looks like we're in luck for the next release. I found that unintuitively I had to add all the commands, again, under the `commandPalette` key of the `menu` contribution point in the manifest. It's there that I could set them to only be available when the editor is working in AutoIt files.

**Comment by loganch** [comment]
Just released the new version, it should address the issues you were having. Let me know if there's anything else I can help with.
