### ISSUE TITLE
Add `Sticky Scroll` support

### ISSUE THREAD

**Issue by Danp2** [loganch/AutoIt-VSCode#128]
[Sticky scroll](https://code.visualstudio.com/updates/v1_71#_sticky-scroll) was added to VSCode a few releases ago. It would be a nice enhancement if this extension added support for this feature.

**Comment by vanowm** [comment]
Since there is no language server, we might have to wait for [#157165](https://github.com/microsoft/vscode/issues/157165) go live

**Comment by Danp2** [comment]
AFAICS, [#159198](https://github.com/microsoft/vscode/pull/159198) is already included in v1.72, Which has been out for around a month. Perhaps the feature needs to be enabled. <shrug>

**Comment by vanowm** [comment]
- To verify, open a file for which you do not have an extension containing a language server installed.
      - Verify that there is no outline in the explorer view
      - Verify that when you scroll the sticky lines are pinned at the same positions as the default start lines of the folding ranges

_Originally posted by @aiday-mar in https://github.com/microsoft/vscode/issues/157165#issuecomment-1260570993_

Sounds like it should be automatic.

**Comment by Danp2** [comment]
>   - Verify that there is no outline in the explorer view

Does this mean that the Outline section should be empty or that it should be hidden by unchecking that option? Not working for me either way.

**Comment by vanowm** [comment]
My bad, the extension does have language server...

**Comment by Danp2** [comment]
@loganch  Any idea how difficult it would be to add support for this?

**Comment by loganch** [comment]
So, I figured that Sticky Scroll was connected with the Symbol Information, and it wasn't working because currently we only have the symbol provider grab the location of the start of the function. I added a function to run a regex to get the whole range of a function to test it out, and looks like we not only get Sticky Scroll, but also nested symbols in the outline, which I've been wanting to see.

**Comment by vanowm** [comment]
Maybe something similar can be done about code folding (#89)?

Also, Autoit seems to have tendency use very long `while` loops, should they also be included in sticky scroll?

**Comment by loganch** [comment]
From what I'm seeing, Sticky Scroll is either working from Symbols (that have a range) OR indentation rules. After pasting some AutoIt code into a new editor without saving there was nothing in the Outline pane, but Sticky Scroll seemed to be working for the loops,

**Comment by vanowm** [comment]
I can't find any documentation for developers regarding sticky scroll...is it "automatic" or can extension populate outline pane and have sticky scroll based on indentation?

**Comment by Danp2** [comment]
> looks like we not only get Sticky Scroll, but also nested symbols in the outline, which I've been wanting to see.

@loganch I observed one issue with the way this currently works. The nested symbol only appears for the first instance when you have the same variable / parameter used in multiple functions. For example --

```autoit
Func _WS_EnableVerbose($iVerbose)
	; EXPORT void enable_verbose(intptr_t enabled);
    Local $aCall = DllCall($hWEBSOCKDLL, "None:cdecl", "enable_verbose", _
            "INT_PTR", $iVerbose)
    If @error Then Return SetError(@error, @extended, -1)
    Return $aCall[0]
EndFunc

Func _WS_RegisterOnConnectCB($hFunc)
    Local $aCall = DllCall($hWEBSOCKDLL, "USHORT:cdecl", "websocket_register_on_connect_cb", _
            "ULONG", DllCallbackGetPtr($hFunc))
    If @error Then Return SetError(@error, @extended, -1)
    Return $aCall[0]
EndFunc

Func _WS_RegisterOnFailCB($hFunc)
    Local $aCall = DllCall($hWEBSOCKDLL, "USHORT:cdecl", "websocket_register_on_fail_cb", _
            "ULONG", DllCallbackGetPtr($hFunc))
    If @error Then Return SetError(@error, @extended, -1)
    Return $aCall[0]
EndFunc
```

In the outline, `$aCall` is only visible under _WS_EnableVerbose and `$hFunc` is only visible under _WS_RegisterOnConnectCB

**Comment by loganch** [comment]
I'm pretty sure that's due to the way that I have the extension find variables for symbols, it currently only keeps the first instance from the whole file.

**Comment by Danp2** [comment]
@loganch Thanks for the explanation. Do you think this functionality should be adjusted so that all of the nested symbols will be correctly displayed?

**Comment by loganch** [comment]
Yeah, I definitely want to fix it. 

I'm working on it right now and have removed the part of the code that stops a symbol from being generated for a variable if something with the same name has been found, but of course it's now giving multiple symbols of the same variable within each function, so I need to refine the way they're found and filtered.

**Comment by Danp2** [comment]
@loganch I just tried running your latest changes, and now I'm getting an exception when I try to launch the extension. Any ideas on how to resolve?

```
Exception has occurred: TypeError: Cannot assign to read only property 'name' of function 'function r(e,r,p,i){if("string"==typeof e&&(e=function(e){e=unescape(encodeURIComponent(e));const t=[];for(let ...<omitted>...)}'
t h (c:\Program Files\Microsoft VS Code\resources\app\extensions\microsoft-authentication\dist\extension.js:1:612179)
	at 5820 (c:\Program Files\Microsoft VS Code\resources\app\extensions\microsoft-authentication\dist\extension.js:1:612299)
	at r (c:\Program Files\Microsoft VS Code\resources\app\extensions\microsoft-authentication\dist\extension.js:1:668793)
	at 9736 (c:\Program Files\Microsoft VS Code\resources\app\extensions\microsoft-authentication\dist\extension.js:1:645023)
	at r (c:\Program Files\Microsoft VS Code\resources\app\extensions\microsoft-authentication\dist\extension.js:1:668793)
	at c:\Program Files\Microsoft VS Code\resources\app\extensions\microsoft-authentication\dist\extension.js:1:669634
	at c:\Program Files\Microsoft VS Code\resources\app\extensions\microsoft-authentication\dist\extension.js:1:670609
	at Object.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\microsoft-authentication\dist\extension.js:1:670715)
	at Module._compile (node:internal/modules/cjs/loader:1165:14)
	at Object..js (node:internal/modules/cjs/loader:1220:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at node:internal/modules/cjs/loader:876:12
	at Function.<anonymous> (node:electron/js2c/asar_bundle:5:13343)
	at Function.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:116:14565)
	at Function.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:65015)
	at Function._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:64383)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Function.r [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:5:101)
	at p._loadCommonJSModule (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:66574)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Promise.all (index 0)
```

**Comment by Danp2** [comment]
FYI, code that is commented via `#cs` / `#ce` is still being included in the Outine pane.
