### ISSUE TITLE
Function parameters aren't availables in intellisense

### ISSUE THREAD

**Issue by Worlor** [loganch/AutoIt-VSCode#13]
Hello,
First thank you for this extension that really make coffee :laughing: 

Ok I think I have found a issue (or maybe an improvement ;) ), the parameters name are not accessible in intellisense within the functions, they don't appear in the list.

![image](https://cloud.githubusercontent.com/assets/3814031/26831475/b8a50268-4acc-11e7-8d55-add98f5b759b.png)
Here the $sUser variable is not recognized

Can you look at this ?
Thanks

**Comment by RonildoSouza** [comment]
Thanks. I'll check.

**Comment by RonildoSouza** [comment]
#17

**Comment by loganch** [comment]
Thanks for submitting the issue! I just published the latest version with the fix.
