### ISSUE TITLE
SmartHelp ignores "include" paths

### ISSUE THREAD

**Issue by vanowm** [loganch/AutoIt-VSCode#136]
Originally posted by @Danp2 at #134.

> * Errors related to smarthelp where full path isn't provided for .au3 file (these files are located in one of the `autoit.includePaths` paths).
> 
> Example setup config --
> 
> ```json
>        "autoit.smartHelp": {
> 			"_AD_": {
> 				"chmPath": "C:\\Users\\danpo\\AppData\\Autoit.Advanced.Help\\AD.chm",
> 				"udfPath": [
> 					"AD.au3"
> 				]
> 			},
> 			"_OL_": {
> 				"chmPath": "C:\\Users\\danpo\\AppData\\Autoit.Advanced.Help\\OutlookEX.chm",
> 				"udfPath": [
> 					"OutlookEX.au3",
> 					"OutlookEX_Base.au3"
> 				]
> 			},
> 			"_TS_": {
> 				"chmPath": "C:\\Users\\danpo\\AppData\\Autoit.Advanced.Help\\TaskScheduler.chm",
> 				"udfPath": [
> 					"TaskScheduler.au3"
> 				]
> 			},
> 			"_WD_": {
> 				"chmPath": "C:\\Users\\danpo\\AppData\\Autoit.Advanced.Help\\Webdriver.chm",
> 				"udfPath": [
> 					"C:\\Users\\danpo\\OneDrive\\Documents\\GitHub\\WebDriver\\wd_core.au3",
> 					"C:\\Users\\danpo\\OneDrive\\Documents\\GitHub\\WebDriver\\wd_helper.au3",
> 					"C:\\Users\\danpo\\OneDrive\\Documents\\GitHub\\WebDriver\\wd_cdp.au3"
> 				]
> 			}
> 		}
> ```
> 
> Notification show in VS GUI -- `File "C:\Program Files (x86)\AutoIt3\Advanced.Help\HelpFiles\OutlookEX.au3" not found (autoit.smartHelp._OL_.udfPath[0])`

Currently `smartHelp` searches files only inside `Advanced.Help\\HelpFiles\\` directory of `AutoIt3.exe` path, it should also search inside `includes` directories

**Comment by Danp2** [comment]
To clarify, this was working correctly in v1.0.8 so I believe it was affected by the relative path modifications.

**Comment by Danp2** [comment]
Thanks for the quick fix. This can be closed now.
