### ISSUE TITLE
build error jump to the line in the code

### ISSUE THREAD

**Issue by bladem2003** [loganch/AutoIt-VSCode#145]
When there is a build error and I click on the line that contains the error it doesn't jump to the line in the code. Is there a way to make jump like in scite?

![Screenshot_37](https://user-images.githubusercontent.com/47271861/208445943-e39e072d-9fbe-4361-940f-d0091d7bf525.png)

**Comment by loganch** [comment]
Yeah according to this issue for VSCode: https://github.com/microsoft/vscode/issues/586, it's on the backburner and is inconsistent for the various ways that people have been expecting for it to work based on format of the text alone...

**Comment by loganch** [comment]
The other problem I'm seeing is that I'm quite sure that error should be showing up in the Problems tab, which would link directly to that line, but that's not happening for me in testing the extension, so I have some investigating to do on that.

**Comment by loganch** [comment]
Yep, looks like the functionality added to work with the paths caused the `enableDiagnostics` setting to always show as undefined/false. I made a fix so that it should be showing up right on the next update.
