### ISSUE TITLE
Suggestions loading very slowly

### ISSUE THREAD

**Issue by ghost** [loganch/AutoIt-VSCode#147]
Starting with version v1.0.9 and including v1.0.10 it takes about 30 seconds for some scripts to show the suggestions after pressing Ctrl+Space. If I revert to version v1.0.8 I get the suggestions immediately.

What can I do, on providing the required informations to solve this issue?

**Comment by MrChiliCheese** [comment]
I guess it is related to commit e000438. With the old version pattern it takes 37.2ms in my script; the new one takes 39.8s.

**Comment by Danp2** [comment]
Wow... that's a huge difference. I don't observe this on my end. Can you replicate with any script or just a specific one?

**Comment by MrChiliCheese** [comment]
I guess the positive lookahead just takes time. If you want to test, you can use this code:
`Local $sgMatchMe_1 = StringReplace("NotMe", "$NotMe_1", 'NotMe') & $ButMe_1`
and repeat it a couple of thousand times, like I did [here](https://regex101.com/r/s4ubek/1).

**Comment by Danp2** [comment]
OIC. When I initially tested, I pressed Ctrl+Space on an empty line and the popup appeared quickly.

**Comment by Danp2** [comment]
This works better for me --

`const variablePattern = /(?:["'].*?["'])|(\$\w+)/g;`

**Comment by MrChiliCheese** [comment]
Yes, that is way better. I was also playing around, but did not find a better solution (my approach was `(?:["'].*["'])|(\$\w+)`)

**Comment by Danp2** [comment]
Further testing has revealed an issue this proposed change. When `showVariablesInGoToSymbol` is enabled, the quoted strings are being included as variables. Anyone know why this would be happening?

**Comment by MrChiliCheese** [comment]
I think switching to regex.exec might be the best approach.

**Comment by Danp2** [comment]
@MrChiliCheese Probably true, but I took the easy route and simply ignored some delimiters. The change is already in the master branch, so let me know if encounter any issues with it.
