### ISSUE TITLE
Issues with Go To Definition

### ISSUE THREAD

**Issue by Danp2** [loganch/AutoIt-VSCode#153]
While testing the Go To Definition functionality, I encountered the following issues --
- Doesn't work for arrays
- Doesn't work for parameters
- Doesn't work on enums
- Doesn't work when declarations are continued onto multiple lines
- Incorrectly locates variables in commented text / header

Many of these limitations are caused by the existing regex implementation, which is --

```
      defRegex = new RegExp(`((?:Local|Global|Const)\\s*)?\\${lookup}\\s+?=?`, 'i');
```

**Comment by Danp2** [comment]
> Incorrectly locates variables in commented text / header

This is also true for Functions. I used the simple example below to test.

```autoit

#cs
	Func test()                                        ; Pressing F12 jumps to here
		ConsoleWrite('fake test' & @crlf)
	Endfunc
#ce


test()                                                 ; Place cursor on this line and press F12
	
Func test()                                            ; Target function
  ConsoleWrite('real test' & @crlf)
EndFunc
```

**Comment by GrandStrateguerre** [comment]
Hello,
there is also a problem when you use ALT+ F12 with :
![image](https://user-images.githubusercontent.com/86523070/226093185-1fb690ca-5949-4f6c-b933-28647716cb44.png)

It seems to work good when the function is called ouside the file. But in this case the function is located in the same file and the function is not detected.

Best regards,

Eric
