### ISSUE TITLE
Need to reinstall the extension on every run

### ISSUE THREAD

**Issue by RickRack1** [loganch/AutoIt-VSCode#162]
Hello, lately I'm having issue with the extension as I have to reinstall it on every restart of VS code. Other extensions work just fine

**Comment by Danp2** [comment]
FWIW, I haven't run into this issue. Have you checked to see if the extension is hidden, but still active?

You may want to include some additional details, such as --

- Extension version
- VSCode version
- VSCode installation method (standard vs portable)

**Comment by RickRack1** [comment]
Extension version is v1.0.10
VSCode version is v1.74.3

And it is the standard installation method.

It installs just fine, which I notice because it does AutoIt Syntax highlighting, but as soon as I restart VS code then the code goes full blank and the extension cannot be seen as installed anymore. Thanks for your help!

**Comment by Danp2** [comment]
IDK. Perhaps checking the logs would yield some useful details. 🤷‍♂️

**Comment by RickRack1** [comment]
So when I restart VSCode I get this message in logs

2023-01-24 23:28:31.038 [info] Extension host terminating: received terminate message from renderer
2023-01-24 23:28:31.045 [info] Extension host with pid 19052 exiting with code 0

Assuming I looked in the right file (exthost.log)

**Comment by RickRack1** [comment]
Seems like installing from a VSIX file did the trick. Working perfectly now. Thanks again for your help
