### ISSUE TITLE
Indent behaviour changes also for other languages

### ISSUE THREAD

**Issue by segelkma** [loganch/AutoIt-VSCode#165]
Hi there,
upon installing the plugin the indent behaviour within VS Code changes from using 4 spaces to a full tab. This applies to all languages being used, which is not a problem for most, but catastrophic for python development. I wouldn't want to disable the plugin every time I code in python, is there a way to fix this? I did not find a setting for this.
In best case, the indent change would only be applied to au3 files in my opinion.

Thanks

**Comment by Marian-Umeleon** [comment]
Thank you! Looks good. Still tabs in au3 files, now spaces in py files

**Comment by vanowm** [comment]
Why does this override editor's settings in the first place? This should be left for the user to decide...

I can't speak for others, but it was very puzzling to me why my editor would not remember my settings after restart...

This whole section should be removed:
```json
    "configurationDefaults": {
      "[autoit]": {
        "editor.detectIndentation": false,
        "editor.tabSize": 4,
        "editor.insertSpaces": false
    },
```

**Comment by loganch** [comment]
I was trying to have it format scripts in AutoIt/SciTe/Tidy standards, but definitely didn't intend for it ignore settings.

**Comment by vanowm** [comment]
I see. As it works right now, when you change settings via statusbar (or via command line)
![image](https://user-images.githubusercontent.com/511517/236698571-2795a69b-6088-494c-b6ae-d7ed9f8390d9.png)
it doesn't remember them after editor restart.

Hopefully VSCode allow overwrite them, but it's a bit involved and not quiet straight forward or intuitive:
![image](https://user-images.githubusercontent.com/511517/236698823-e17b8643-bdd5-4d31-a9cd-ce133ce5c03e.png)
One need hover over `Modified elsewhere` and then click on `Autoit`

Perhaps this should be "fixed" on VSCode side then, if something is overwriting settings from different scopes, then changing it via command line should be done in that scope and not globally?
