### ISSUE TITLE
Massive errors when loading AddOn

### ISSUE THREAD

**Issue by dcc1165** [loganch/AutoIt-VSCode#168]
Recently, when I start VS Code, your extension complains:
`File "" not found (autoit.kodaPath`
`File "" not found (autoit.infoPath)`
`File "" not found (autoit.helpPath)`
`File "" not found (autoit.checkPath)`
`File "" not found (autoit.wrapperPath)`
`File "C:\Program Files (x86)\AutoIt3\AutoIt3.exe" not found (autoit.aiPath)`

Perhaps you didn't realize VS Code runs on more than just Windows?  A VERY common use-case is to work on source code on a desired OS (i.e. Linux or MacOS), then run/test/etc elsewhere (Vagrant, Windows VM, etc)...Many of us have no intention of running on our development machine, which means not all of us are pigeon-holed into ONLY Windows.  You need to better define your extension validation.  If it's not Windows, don't bother checking the Windows-only junk.

This issue is so intrusive I had to disable the AutoIT extension because those error pop up while editing and (especially) when initially starting VS Code or opening a new window.

**Comment by Danp2** [comment]
You bring up a valid point. However, I wonder if you've ever heard the proverb "you can catch more flies with honey than with vinegar"? 🤔 💭 😉

**Comment by dcc1165** [comment]
Not even close to "vinegar".  You don't want to see an example of that, believe me.  Software, regardless of "price" (commercial, open source, etc), shouldn't be let out the door with such a basic fixable flaw (call it a bug or a crappy feature...your choice) -- it's not like it's some low-level obscure bug that can only be reproduced when a finite set of circumstances occur at the same point in time (those are "fun" to find...lol).

**Comment by Danp2** [comment]
May not be "vinegar", but definitely rude and condescending IMNSHO. I look forward to seeing your contribution to this project that addresses these shortcomings instead of simply complaining about them. 😀

**Comment by dcc1165** [comment]
I'm not going to derail this into some silly flame-war.  FWIW, I don't contribute pull-requests to fix something that should've been easily caught in simple unit testing (unless, of course, I'm an active maintainer).  If I were to do that, I'd implement my own version (as I've done countless times over the past 40+ years)

**Comment by olaf-k** [comment]
> I'm not going to derail this into some silly flame-war. FWIW, I don't contribute pull-requests to fix something that should've been easily caught in simple unit testing (unless, of course, I'm an active maintainer). If I were to do that, I'd implement my own version (as I've done countless times over the past 40+ years)

the Karen-level of entitlement, inappropriate inflammatory criticism and childish bragging are horrific.
I stumbled here to report the path issue (AutoIt allows custom installs without some of the tools, such as the wrapper or Koda), saw yours, and now I'm half hoping @Danp2 won't solve it just to irk you. incredible.

**Comment by dcc1165** [comment]
"Karen-level entitlement"?  ROFL...that's the funniest thing I've heard from a script-kiddie in decades.  Way to hide behind the keyboard.  Personally, I don't care if it's fixed -- my problem with this is lack of testing and the narrow-minded approach in thinking these tools run on a single OS (hardcoding C:\<anything> is just short-sighted).  The fact is, AutoIt simply isn't a thing anymore for most people due to other, more mature scripting languages (PowerShell, Python, Ruby, etc).

**Comment by vanowm** [comment]
Personally I didn't realize non-windows users would need this extension. This extension relies on AutoIT installation to validate the code / syntax check...

I guess for non-windows users it can only be used for syntax highlighting.
