### ISSUE TITLE
Add please Tidy script designer hotkey!

### ISSUE THREAD

**Issue by Se7enstars** [loganch/AutoIt-VSCode#170]

**Comment by loganch** [comment]
Haven't heard of that one and my Google-fu is failing me, can you point me towards what Tidy script designer is and which hotkey it uses, I'm assuming from the SciTe editor?

**Comment by Se7enstars** [comment]
Yes it's script designer bro
![image](https://user-images.githubusercontent.com/20016371/224344826-621527cf-3c02-454f-8767-a80df00980b1.png)

(C:\Program Files (x86)\AutoIt3\SciTE\Tidy) - If installed Scite4Autoit it's will be available at menu of Scite

**Comment by Danp2** [comment]
Tidy is already available via this extension. You can even assign it your own shortcut by doing the following --

- Press `Ctrl+Shift+X` to switch to Extensions in the side bar
- Find this extension in the list 
- Click the gear icon in the bottom right corner
- Select the `Extension Keyboard Settings` option
- Choose your own keybinding for the `AutoIt: Tidy` entry

HTH, Dan

**Comment by Se7enstars** [comment]
OK thanks assigned to it: ctrl+alt+T

**Comment by Danp2** [comment]
FWIW, you can also access Tidy by using the Command Palette (Ctrl+Shift+P).
