### ISSUE TITLE
Shortcut Open Include file does not work on VS Code 1.76.1

### ISSUE THREAD

**Issue by GrandStrateguerre** [loganch/AutoIt-VSCode#171]
Hi,

VS Code :
![image](https://user-images.githubusercontent.com/86523070/224489938-ebc35366-769c-4cb8-9bc1-eaeee673e789.png)

F5 works good :
![image](https://user-images.githubusercontent.com/86523070/224490034-3c75de9c-b17b-425f-8bd8-0ce29f4b79aa.png)

When I press ALT + I  on line :
![image](https://user-images.githubusercontent.com/86523070/224490125-c6c6628e-3d2d-4a2b-a38b-3a1d29dc9457.png)
I get this error :
![image](https://user-images.githubusercontent.com/86523070/224490100-96409d19-a224-4b75-a090-79d6441dba4a.png)

Best regards

**Comment by Danp2** [comment]
@GrandStrateguerre It should work if you add the target directory to the settings.json file. For example --

```json
    "autoit.includePaths": [
	  "C:\\Program Files (x86)\\AutoIt3\\Include",
          "C:\\Users\\xxxxx\\Dropbox\\Autoit UDFs"
    ],
```

I can't recall if it was originally designed to work without this modification.

**Comment by GrandStrateguerre** [comment]
Hello Danp2,

By default the setting include paths is empty. I set the path "C:\\Program Files (x86)\\AutoIt3\\Include" in the config , and it works, Thanks.

Should be added by default, I think ?

For others to do the settings :
![image](https://user-images.githubusercontent.com/86523070/224495681-c485eaf4-6a0f-481a-b121-020e64f014cd.png)
![image](https://user-images.githubusercontent.com/86523070/224495516-eee9cc15-c909-4120-8e75-92ba7fa67002.png)
![image](https://user-images.githubusercontent.com/86523070/224495530-da19dbf8-7400-4faf-8cdb-7f3d028a4685.png)

Best regards

**Comment by Danp2** [comment]
@GrandStrateguerre This path was originally included by default. This appears to have changed in https://github.com/loganch/AutoIt-VSCode/commit/5903d1165511d9e86f86d950541b7ae823a55c43. Maybe @loganch or @vanowm can provide some input about why this was changed.
