### ISSUE TITLE
ALT+I on Include path like "..\..\##xxx##\xxx.au3" does not work

### ISSUE THREAD

**Issue by GrandStrateguerre** [loganch/AutoIt-VSCode#175]
Hello,

![image](https://user-images.githubusercontent.com/86523070/225912947-a40f2f2d-7c62-49a3-b431-030c63f0eea0.png)

for a path like "..\..\foder\file.au3" the shortcut doesnot work

I also add, the folder path of the include file in  autoit.includePaths :
![image](https://user-images.githubusercontent.com/86523070/225914429-4a399535-79dd-4cf7-896b-4348839a5ea5.png)

But with no sucess.

Best regards

**Comment by Danp2** [comment]
Hi @GrandStrateguerre,

Thanks for the report. Unfortunately, I'm not able to reproduce on this end. I assume that you are running the latest version of this extension. Are you sure that the relative path is valid, filenames are spelled correctly, etc?

FYI, you shouldn't need to add the directory to `autoit.includePaths` for this to work correctly.

Regards, Dan

**Comment by GrandStrateguerre** [comment]
Hello Dan,

I think, I found it, this is when you have a # in the path like :
C:\User\J617670\##ABCD##\....

Since I remove the folder with # , it works good.

Have a good wee-end :)

Thanks, Eric
