### ISSUE TITLE
Compile pathing

### ISSUE THREAD

**Issue by Huesdon** [loganch/AutoIt-VSCode#2]
Compile does not work on a full default install. The compile tools are not in the scite folder.

**Comment by loganch** [comment]
Sorry, the default install of AutoIt3 only includes a lite version of the SciTE setup. The compile tools come with the full install of SciTE4AutoIt3, found [here](https://www.autoitscript.com/site/autoit-script-editor/downloads/), and for now, the extension will depend on that being present.

**Comment by Huesdon** [comment]
Closed, installed correct package, working as intended
