### ISSUE TITLE
Don't autocomplete variables insides arrays bracket

### ISSUE THREAD

**Issue by Worlor** [loganch/AutoIt-VSCode#20]
Hello

I found a bug with Intellisense
![image](https://user-images.githubusercontent.com/3814031/28575675-e7917f74-7151-11e7-85a1-28e7fbf36a21.png)

The extension have indexed this variable used inside brackets for array traversing

Thanks

**Comment by loganch** [comment]
Could you possibly provide me with a file or more of the code to provide me more context, please? I'd love to get to the bottom of this.

**Comment by Worlor** [comment]
Sure

	Local $a1Daffectation[0]
		For $i = 0 To Ubound($aasAffectationEDS) - 1 Step +1 ;Conversion en tableau 1 dimension
			_ArrayAdd($a1Daffectation, $aasAffectationEDS[$i][0])
			_ArrayAdd($a1Daffectation, $aasAffectationEDS[$i][1])
		Next
		_ArraySort($a1Daffectation)

**Comment by Worlor** [comment]
Another one 
![image](https://user-images.githubusercontent.com/3814031/28768104-bb8fc26c-75d6-11e7-9e53-aae0e2970370.png)

**Comment by RonildoSouza** [comment]
If the file (.au3) is not saved the VSCode uses its autocomplete is not the extension (AutoIt).

It is mandatory to save the file for the correct operation of the extension.

**Comment by RonildoSouza** [comment]
![sem titulo](https://user-images.githubusercontent.com/17293460/28781258-d8e4ebc2-75df-11e7-8da6-400ab4f09204.png)

**Comment by RonildoSouza** [comment]
Not Save!

![sem titulo](https://user-images.githubusercontent.com/17293460/28781344-1e3a244e-75e0-11e7-8001-2007cacf514b.png)

**Comment by RonildoSouza** [comment]
This treatment exists so that AutoIt snippets are only displayed for .au3 file extension.

**Comment by loganch** [comment]
Ronildo is right, I tried it out earlier, and it looks like you do get the Syntax highlighting when you manually set the language as AutoIt, but I set all the other functionality to work strictly for .au3 files since I and others do other types of coding in VSCode (like this extension itself in js, for example). Let me know if our explanations are sufficient so that I can close the issue, and thanks for submitting it!

**Comment by Worlor** [comment]
Unterstood, but I have this bug on a saved file, I think something wrong with my VS Code configuration because I don't have the "Variable" word displayed on intellisense.

How can I correct this ?

**Comment by Worlor** [comment]
Huh OK, If I do Ctrl + Esp for autocompletion, it will display the $Var1[27], but if i just type "Va" the autocompletion works well ;)

**Comment by RonildoSouza** [comment]
If the file is saved, it works with or without Ctrl + Space

**Comment by RonildoSouza** [comment]
@Worlor send a Print Screen of the entire VSCode screen with the script open

**Comment by Worlor** [comment]
Thanks for helping,
Here it is 
![image](https://user-images.githubusercontent.com/3814031/28862026-d2186406-7763-11e7-88ab-40cc46259c57.png)


List of extension installed : 
![image](https://user-images.githubusercontent.com/3814031/28862047-e44b7046-7763-11e7-8fca-b573f88433f5.png)

**Comment by RonildoSouza** [comment]
I ran several tests, even simulating a folder structure just like your project, but in all tests intellisense ran normally.

In this way I could not identify any other motive besides what I had already mentioned.

**Comment by Worlor** [comment]
I did some test too, I think the problem come from includes files that are not in the workspace

**Comment by loganch** [comment]
Not the workspace specifically, but right now all include paths are only parsed if they are between quotes (e.g. #include "Example.au3"). The paths are either assumed to be explicit if there is a backslash present or calculated based on the current script's directory. 

It's on my todo to have the extension look in the AutoIt Lib folder for includes between brackets that aren't "built-in" UDFs.

**Comment by Worlor** [comment]
Yes, i have seen that in your code.
I managed to make it work by closing workspace and opening a little au3 file like [this logger lib](https://github.com/Worlor/AutoIt-Logger) 
But after opening some files in the workspace, the extension stop working and the bug come again in all files.

**Comment by Worlor** [comment]
Ok after doing some more test, I think I have found the problem
I have modified the ai_completion.js for extra logging
![image](https://user-images.githubusercontent.com/3814031/29063640-c5452f44-7c26-11e7-92c3-e10c3be2f6c2.png)
Here is a gist : https://gist.github.com/Worlor/1f9be7a01813fd9cc8eb766bc4faf79f

My includes : 
![image](https://user-images.githubusercontent.com/3814031/29063721-05d2380e-7c27-11e7-8528-5e0b507ebb28.png)

And when trying to autocomplete a variable, the extension search in the wrong folder, causing the crash, [see the log here](https://gist.github.com/Worlor/cfe9efd260d7844c89b76b8973262361)

**Comment by Worlor** [comment]
Sometimes I have also this error : 
```
ReferenceError: Range is not defined
    at Object.provideCompletionItems (x:\Quentin-tmp\AutoIt-VSCode\out\src\ai_completion.js:34:13)
    at c:\CAT_USERDATA\Prog\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:355556
    at c:\CAT_USERDATA\Prog\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:63826
    at new n.Class.derive._oncancel (c:\CAT_USERDATA\Prog\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:49058)
    at Object.t.asWinJsPromise (c:\CAT_USERDATA\Prog\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:63789)
    at e.provideCompletionItems (c:\CAT_USERDATA\Prog\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:355510)
    at c:\CAT_USERDATA\Prog\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:364740
    at t._withAdapter (c:\CAT_USERDATA\Prog\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:359002)
    at t.$provideCompletionItems (c:\CAT_USERDATA\Prog\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:364702)
    at t.e.handle (c:\CAT_USERDATA\Prog\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:308956)
```

**Comment by Worlor** [comment]
Well I found the bug, on this function (ai_completion.js l.107) : 
var fileData = fs.readFileSync(filePath)

If the filepath begin by a driveletter in lowercase, there is a bug and it replace it by c:, that's why the extension didn't find my file

I send a PR

**Comment by Worlor** [comment]
#23
