### ISSUE TITLE
Cascaded region not shown correctly in outline

### ISSUE THREAD

**Issue by IronJosie** [loganch/AutoIt-VSCode#211]
It seems like cascaded Region are not shown correctly in the outline:
![image](https://github.com/loganch/AutoIt-VSCode/assets/151548307/a4acda5c-a2c8-4a2b-833a-c53964ed7aa0)

1. Is correct
2. Is correct
3. Is on the same lavel as `Layer A` and `Layer B`

**Comment by loganch** [comment]
Did some poking around and the code I set up to determine Regions isn't sufficient. The regex to capture the length/area of the Regions ends too early and with the trouble I'm having with nesting it will probably require more involved refactoring.
