### ISSUE TITLE
Setting "autoit.outputCodePage" seems to be not working at all 🤔 ?!

### ISSUE THREAD

**Issue by Sven-Seyfert** [loganch/AutoIt-VSCode#212]
### Hi 👋 , first of all:
I really appreciate the VSCode extension and the work behind it, thanks folks 👍 .

### Problem:
The VSCode "OUTPUT"  does not show the correct characters for "simple" german umlauts.

*Reproducer script:*
``` autoit
ConsoleWrite('This is a test of german umlauts. Umlauts: ä ö ü ß. Emoji: 😀' & @CRLF)
```

*Result:*
![grafik](https://github.com/loganch/AutoIt-VSCode/assets/29656921/75ef440f-f064-473e-ac63-11c08c518741)

### Settings:
If I adjust the codepage by setting `autoit.outputCodePage` to `cp850`, `utf8` or `windows1252` nothing changes in the output.

![grafik](https://github.com/loganch/AutoIt-VSCode/assets/29656921/d971ab93-aab6-47d3-a849-d4969a017311)

![grafik](https://github.com/loganch/AutoIt-VSCode/assets/29656921/76d2aed8-b799-49bb-aa40-399b7c7c678a)

❓ The setting seems to be not working at all? Hint: The file encoding in my VSCode is set to `UTF-8`

![grafik](https://github.com/loganch/AutoIt-VSCode/assets/29656921/9117f647-d524-4498-a79d-68ca564cd335)

❓ Do you guys see any issues that I am doing or can you reproduce this behavior?

Thanks for your time and keep staying healthy 😇 .

Best regards
Sven

**Comment by Sven-Seyfert** [comment]
Working [workaround](https://www.autoitscript.com/forum/topic/208189-is-there-a-reason-consolewrite-converts-everything-to-ansi-and-doesnt-support-unicode/?do=findComment&comment=1502009)

``` autoit
Func _Print(ByRef $sData)
    Local Const $iUtf8Flag = 4
    ConsoleWrite(BinaryToString(StringToBinary($sData & @LF, $iUtf8Flag)))
EndFunc
```

**Comment by vanowm** [comment]
Just out of curiosity, does it show correctly in SciTE?

**Comment by Sven-Seyfert** [comment]
Hi @vanowm , the german umlauts yes, but I cannot use emojis at all in SciTE. But I have to say, I didn't used SciTE since years - so maybe my bad in some lack of configuration 🤔 .

Btw: The work-around `_Print()` function also has to be changed for SciTE to the ANSI flag (1) instead of UTF8 (4).

**Comment by Sunev** [comment]
https://github.com/loganch/AutoIt-VSCode/blob/1fc45786a0755426e9a9c4c9a26dfdb0760d6453/src/ai_commands.js#L670-L686
As related lines above, a property named ```config.isCodePage``` was used, but which is not defined in ```package.json```.
https://github.com/loganch/AutoIt-VSCode/pull/217

**Comment by vanowm** [comment]
Actually, this is a regression from ad6c3ebf5978eba74dbe37a7cf4bc51561d59f8b where centralized config was introduced.
[`isCodePage`](https://github.com/loganch/AutoIt-VSCode/commit/ba5811ae2e862d75168b91a52cf0f29356ae7889#diff-846013c48b8ca8e2c3070a8e0a1a4677c2658aa22ea2557373c235b10e130f0c) was generated upon initialization, its purpose was to confirm that chosen `outputCodePage` is valid.

**Comment by Sunev** [comment]
Well, I didn't check commit history.
It seems that ```isCodePage``` don't have a definition at this moment.

**Comment by Sven-Seyfert** [comment]
Hi and thank you @Sunev 👋 . I tested your PR change #217 manually and it works. The setting `Autoit: Output Code Page` with the value `windows1250` leads to correct german umlauts in the output panel 👌 .

What I changed manually to test:
- replace "isCodePage" with "outputCodePage" in file **extension.js** (`C:\Users\your-user-name-here\.vscode\extensions\damien.autoit-1.0.12\dist\extension.js`)
- restart VSCode
- change the mentioned option by the VSCode settings

Without the replacement, the codepage option does not work at all. My research confirmed you assumption about "isCodePage" does not have a definition.

I hope the maintainer(s) will add this fix into the master branch, thanks 😀 .

Best regards
Sven

**Comment by vanowm** [comment]
The only issue with this change is there is no check if `outputCodePage` value is valid or not, which might create errors (?)

**Comment by Sunev** [comment]
I think that won't be a big problem, because those developers who set ```.outputCodeapge``` should be responsible to make sure their inputs correct. And I guess they know what they are doing.

**Comment by vanowm** [comment]
True, however vscode syncs settings between computers, therefore on one system it might be valid, on another might not (hypothetically speaking)

**Comment by Sunev** [comment]
What about to set the default of  ```.outputCodepage``` as ANSI?
Thus most user won't even need to config this.

**Comment by Sunev** [comment]
I recently found that VSCode lets you turn off sync for individual settings with a right-click. So, syncing might not be a big deal.
