### ISSUE TITLE
How can I compile .au3 files directly in visual studio code?

### ISSUE THREAD

**Issue by 3xpla1n** [loganch/AutoIt-VSCode#27]
I installed `autoit` and `scite` and the extension in visual studio code. Intellisense is working fine, but I don't see any option on how to compile the files.  Do I need a `TaskRunner` or is there somewhere a default configuration?

**Comment by loganch** [comment]
Assuming that you're on a 64-bit system and installed AutoIt in the standard place, you should be able to compile your scripts with the `Ctrl+F7` shortcut or by using `Ctrl+Shift+P` to open the Command Palette to search for the "AutoIt: Compile" command.

![image](https://user-images.githubusercontent.com/7883107/29366200-3845b036-824e-11e7-9e63-59e2e0400b7f.png)

**Comment by 3xpla1n** [comment]
After starting my pc today the AutoIt options showed up in visual studio code before they haven't. Now it is working, ty
