### ISSUE TITLE
Intellisense : Don't process parameter inside quotes

### ISSUE THREAD

**Issue by Worlor** [loganch/AutoIt-VSCode#29]
Hello,

I found a bug with the intellisense auto-completion of parameters. 
I use the StringReplace function with a "," in parameter, Intellisense think it's part of the function : 
![image](https://user-images.githubusercontent.com/3814031/33027041-53fca48c-ce12-11e7-8634-b1f306c5a3ad.png)

In this capture, we can see Intellisense autocompleting for the 4th parameter, but only 3 are put.

**Comment by Worlor** [comment]
Without the comma : 
![image](https://user-images.githubusercontent.com/3814031/33027107-8a1014f0-ce12-11e7-93da-727dbe574715.png)

**Comment by loganch** [comment]
I'm aware of and have run into this issue, and it's in my todos to solve.

**Comment by loganch** [comment]
Good news! It looks like I've got it working right on the userSigHelp branch if you want to give it a look and  test it out.

**Comment by Worlor** [comment]
Hello loganch,
I give a try and got some errors : 
````
Échec de l'activation de l'extension 'Damien.autoit' : Cannot find module 'merge-json'.
extensionHostProcess.js:4
Activating extension `Damien.autoit` failed:  Cannot find module 'merge-json'
extensionHostProcess.js:4
Here is the error stack:  Error: Cannot find module 'merge-json'
extensionHostProcess.js:4
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.t.initializeExtensionApi.t.getExtensionPathIndex.then.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:498891)
	at Module.require (module.js:498:17)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (x:\Quentin-tmp\AutoIt-VSCode\out\src\ai_signature.js:4:17)
	at Object.<anonymous> (x:\Quentin-tmp\AutoIt-VSCode\out\src\ai_signature.js:172:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
Object
message:"Git error"
stdout:""
stderr:"fatal: Invalid path 'c:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/parts/welcome/page': No such file or directory
"
exitCode:128
````

VSCode 1.18

**Comment by Worlor** [comment]
Hello loganch,
I tried this new branch, and this time, it stay on the first argument
![image](https://user-images.githubusercontent.com/3814031/33165892-b4a314f6-d038-11e7-9328-b582208758b0.png)

Sorry, I currently don't have much time to help you

**Comment by loganch** [comment]
Did some more work to make it better at detecting the function being called for.

**Comment by Worlor** [comment]
Hello loganch,

I tried it on my project
![2017-11-28_09-48-05](https://user-images.githubusercontent.com/3814031/33310288-628fbca4-d421-11e7-89df-2130f4df9a33.gif)

On the other hand, I tried the autocompletion of function parameters in user included files and it works nice ! good job

**Comment by loganch** [comment]
Have you had a chance to try out the latest updates?

**Comment by Worlor** [comment]
Hello loganch,

I'm just trying it, but the bug is fixed
![image](https://user-images.githubusercontent.com/3814031/33880454-f0b049de-df31-11e7-83de-979ac577ae25.png)

Good job, i close
