### ISSUE TITLE
Console output?

### ISSUE THREAD

**Issue by Huesdon** [loganch/AutoIt-VSCode#3]
Having access to a real time console for script output (similar to ISN Autoit Studio) is essential. I am not sure if this is in.

**Comment by loganch** [comment]
This isn't in yet, but definitely a good idea! Now to learn how to do more with Node launching applications.

**Comment by Huesdon** [comment]
Nice update man, I am trying to move into your plugin from AutoitStudio, I'm missing the live console output though (mostly so you can debug with consolewrite rather than msgbox.)

**Comment by Huesdon** [comment]
Apologies for beating this one to death. I am trying to use this soo bad as working from vscode will make my life easier considering my project. 
**Example issue**: I am working in a test.au3 file, I run the script, it quits with no messages. Zero feedback as to why it exits. I open and run in Scite, console clearly shows that I was missing an include file. I don't know how to develop without a console showing me stdout and stderr.

**Comment by loganch** [comment]
That's odd, it's not showing any output from running the script at all on version 0.09? I'm pretty sure I implemented that.

**Comment by Huesdon** [comment]
I notice that sometimes when the script halts all the output spews into the console, but not during runtime.

**Comment by Huesdon** [comment]
Thought I would test with vscode 1.9 that was just released. As I described above, I launch my script, it runs, but no output at all to the autoit output terminal in the editor. I right click kill the script from it's icon in the system tray and then it spews...

> +>18:26:33 Starting AutoIt3Wrapper v.16.612.1119.0 SciTE v.3.6.6.0   Keyboard:00000409  OS:WIN_10/  CPU:X64 OS:X64  Environment(Language:0409)  CodePage:  utf8.auto.check:
+>         SciTEDir => C:\Program Files (x86)\AutoIt3\SciTE   UserDir => C:\Users\Hue\AppData\Local\AutoIt v3\SciTE\AutoIt3Wrapper   SCITE_USERHOME => C:\Users\Hue\AppData\Local\AutoIt v3\SciTE 
>Running AU3Check (3.3.14.2)  from:C:\Program Files (x86)\AutoIt3  input:e:\Code\dolores\dEngine\dEngine.au3
+>18:26:34 AU3Check ended.rc:0
>Running:(3.3.14.2):C:\Program Files (x86)\AutoIt3\autoit3.exe "e:\Code\dolores\dEngine\dEngine.au3" $(1) $(2) $(3) $(4)
--> Press Ctrl+Alt+Break to Restart or Ctrl+Break to Stop
Entered connectIRC()
Starting TCP
Connecting to IRC server
Joining channel...
Sending Hello message...
+>18:27:11 AutoIt3.exe ended.rc:0
+>18:27:11 AutoIt3Wrapper Finished.

**Comment by loganch** [comment]
I've looked into and I have an update coming soon where I've reworked the extension to pipe stdout to the output window as it comes in.

**Comment by Huesdon** [comment]
you sir, are a stud. Thanks man, this makes a huge difference.

**Comment by loganch** [comment]
Pushed a new update today, let me know if it works for you.

**Comment by Huesdon** [comment]
Simply. Awesome. You have now saved me from having to run multiple code editors. I am working with python and autoit from the same window and the git support in vscode makes it all come together. Thank you sir. Closing issue.
