### ISSUE TITLE
Intellisense not working with AutoIt Custom Includes Folder

### ISSUE THREAD

**Issue by Sharrq** [loganch/AutoIt-VSCode#31]
So I noticed that the extension will read in the functions and provide Intellisense/Call Hints for includes if they are included using the relative path ...

i.e. #include "UDF.au3" or #include "../UDF.au3"

But if you setup an additional includes directory by setting it in the registry per AutoIt's instructions

"There is a special registry value that can be created at "HKEY_CURRENT_USER\Software\AutoIt v3\AutoIt" called "Include". It should be a REG_SZ (string) value. The contents of this value are a semi-colon delimited list of directories that should be searched for files when resolving #include's in addition to the standard locations."

and therefore include it as #include <UDF.au3>, then the Intellisense doesnt work. Builds and compiles work fine, but intellisense doesnt unless I refer to it using relative paths or its in the default AutoIt includes folder. 

Can the extension be updated to read that registry key and include those paths as well for Intellisense? Or is there somewhere in the extension that I can declare that folder path to get this to work?

**Comment by loganch** [comment]
I can definitely update the extension to read from other places. I've done some research on reading from the registry, though it doesn't seem straight-forward or ideal to get working in Node/JavaScript, so I'm leaning more towards a list of directories within an option for the extension.

**Comment by Sharrq** [comment]
that would be fine with me. thanks for the response!

**Comment by loganch** [comment]
I believe I've addressed this in the latest release, let me know it works for you.

**Comment by Sharrq** [comment]
Yep, i just added the path and it is working. Thanks!
