### ISSUE TITLE
Keyboard shortcut to terminate process

### ISSUE THREAD

**Issue by IgorGee** [loganch/AutoIt-VSCode#33]
My keyboard is ahead of its time and doesn't have a Break key.

I'm an awful developer that frequently writes scripts that never terminate :)

Would adding a shortcut like this be possible?

Please and thank you.

**Comment by loganch** [comment]
Sorry for the delayed response, but you can change the keyboard shortcut in an INI for AutoIt3Wrapper, details at this [link](https://www.autoitscript.com/autoit3/scite/docs/SciTE4AutoIt3/AutoIt3Wrapper.html).
