### ISSUE TITLE
Autocomplete : function beginning with "__" bug

### ISSUE THREAD

**Issue by Worlor** [loganch/AutoIt-VSCode#34]
Hello

I found a bug with autocomplete when function began with two underscore : __

Only one is detected, causing a function rewrited with 3 underscore when enter is hit
![image](https://user-images.githubusercontent.com/3814031/40168334-8618819c-59c3-11e8-9592-190ee9ce9acc.png)

![image](https://user-images.githubusercontent.com/3814031/40168425-b65e21ea-59c3-11e8-881d-5a78b222327f.png)

__error function is inside the document

**Comment by loganch** [comment]
It was an issue with my regex pattern for Words as defined in the extension. Just updated it and pushed the change to Github.

**Comment by loganch** [comment]
Just put out the release that should fix that.

**Comment by Worlor** [comment]
It works, good job !
