### ISSUE TITLE
VSIXInstaller.NoApplicableSKUsException on VS 2015

### ISSUE THREAD

**Issue by grackov** [loganch/AutoIt-VSCode#37]
I am trying to install on a standalone client Windows 7 Prof with VS2015 v3. I have the Damien.autoit-0.2.0.vsix file and get the following exception.
VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products 
Is there a way to get around this exception?

**Comment by loganch** [comment]
VS2015 v3? The problem might be that this extension is for the Visual Studio Code editor, not the Visual Studio IDE.

**Comment by loganch** [comment]
@grackov Was I correct in my assumption?

**Comment by grackov** [comment]
Due to my working environment conditions I am unable to download VS Code Editor. I was able to edit the manifest to get it to install into my IDE. But since it is written in JavaScript and I don't have those extensions installed the IDE does not know what to do with it. I work primarily in C# so that is all I have installed and have no internet accessibility. So at this juncture I don't see a way ahead. Suggestions?

**Comment by loganch** [comment]
Perhaps the extension will do something for you? https://marketplace.visualstudio.com/items?itemName=DavidRoller.AutoItSyntaxHighlight

**Comment by grackov** [comment]
Yes, using the vsix extension was the way I was able to get it into the IDE. It shows it as installed in the extension panel but the tool does not show up anywhere.

**Comment by loganch** [comment]
Sorry for the late reply, @grackov, but I this extension is for Visual Studio Code, not VS2015 or the newer IDEs, and I can't really provide support for that other extension.
