### ISSUE TITLE
How to pass parameters to the script?

### ISSUE THREAD

**Issue by cedrou** [loganch/AutoIt-VSCode#38]
I have a script that can take parameters from the command line and I'd like to debug it from VSCode.

From what I see in the Output panel, it look like this could be possible, because the parameters "$(1)" to "$(4)" are always put on the command line:
```
+>13:29:15 Starting AutoIt3Wrapper v.18.708.1148.0 SciTE v.4.1.0.0   Keyboard:0000040C  OS:WIN_10/  CPU:X64 OS:X64  Environment(Language:0409)  CodePage:  utf8.auto.check:
+>         SciTEDir => C:\Program Files (x86)\AutoIt3\SciTE   UserDir => C:\Program Files (x86)\AutoIt3\SciTE\AutoIt3Wrapper
>Running AU3Check (3.3.14.5)  from:C:\Program Files (x86)\AutoIt3  input:e:\dev\script.au3
+>13:29:16 AU3Check ended.rc:0
>Running:(3.3.14.5):C:\Program Files (x86)\AutoIt3\autoit3_x64.exe "e:\dev\script.au3" $(1) $(2) $(3) $(4)
--> Press Ctrl+Alt+Break to Restart or Ctrl+Break to Stop
+>13:35:09 AutoIt3.exe ended.rc:0
+>13:35:09 AutoIt3Wrapper Finished.
Process exited with code 0
```

How can I change these parameters "$(1)" to "$(4)" ? And am I limited to 4 parameters ?

**Comment by loganch** [comment]
So I did some research and found two threads that made realize that I didn't implement that part of running scripts properly. Basically, the $(1) to $(4) were originally variables to be filled in by using the _View->Parameters_ option in SciTe, which is limited to 4 entries. Right now I'm just passing the literal strings, which I'm going to remove and work on adding an option to set parameters in VSCode.

While waiting for that, you could have your code look to an array that is assigned to either the default $CmdLine or the parameters you want to test (when $CmdLine is empty).

Here are the threads I found:
https://www.autoitscript.com/forum/topic/129716-testing-an-autoit-program-with-command-line-args/
https://www.autoitscript.com/forum/topic/123036-simulating-command-line-parameters/

**Comment by cedrou** [comment]
OK. I already have a workaround in my code to simulate script parameters, but I'm looking forward to your integration in VSCode.

Thanks.

**Comment by hairlesshobo** [comment]
@loganch Any update on this? It appears that you made the change in code, and the readme file even shows that it is available in 0.2.1, but I haven't found a release with that version. Are you going to be releasing a new version soon by chance? I am currently unable to use VSCode for developing my AutoIt scripts because they all require command line parameters to be passed.

Thanks!!

**Comment by loganch** [comment]
@hairlesshobo Sorry, I've been bogged down with other life stuff and was trying to fit more into 0.2.1, but I'm going to run through and make sure what I have implemented works, then release it.

**Comment by hairlesshobo** [comment]
No problem at all, I totally understand about life. Thank you for knocking this out so quickly!!

**Comment by loganch** [comment]
@hairlesshobo & @cedrou, Have you had a chance to try out the new functionality? I'd like to see if I can go ahead and close this issue.

**Comment by hairlesshobo** [comment]
@loganch I have tried it out and it does work for sure. There is one thing that I am not sure if you overlooked or decided to not implement for some reason. Once you have specified the command line arguments, if you go back to change those arguments, the box starts off empty again. I would have assumed that, at least so long as the VSCode session has not been ended, the provided arguments would be automatically re-entered into the field. Thoughts?

**Comment by cedrou** [comment]
I just tried it and when I give flags that start with `/` or `-` these characters are removed from the command line. I need to enclose them in quotation marks to make it work. 

I also agree with @hairlesshobo that the `Shift+F8` box should start prefilled with the current command line.

**Comment by loganch** [comment]
Let me know if the latest update takes care of the issue
