### ISSUE TITLE
Add "Go to definition"

### ISSUE THREAD

**Issue by guigeek34** [loganch/AutoIt-VSCode#39]
Can you add "Go to definition" feature, with shortcut "F12", like in other language ?

**Comment by guigeek34** [comment]
In AutoIt, this feature is assigned on shortcut Ctrl+J.

**Comment by loganch** [comment]
Yep it's part of the VSCode API, so I should be able to get that working

**Comment by carloselectro** [comment]
Yes please add this feature.

**Comment by foxxycodes** [comment]
I would really appreciate this feature too.

**Comment by loganch** [comment]
Added into v0.2.3

**Comment by Sven-Seyfert** [comment]
**Hi and sorry Logan**,

your fix in file `src\ai_definition.js` for adding "Go to definition" seems to be uncomplete. It works for definitions in the same file which is the usage of the function. But when I have the definiton in a separate file which is also located in the workspace and on the same level, I can not do the "jump" to that file.

It doesn't work unfortunatly.

---

I really tried to do it on my own and set a pull request then, but I couldn't achieve the correct result.
I tried to combine code of `src\ai_definition.js` and `src\ai_workspaceSymbols.js` to iterate through all files, but I loosed.

If you need more information, please let me know.
Thanks for your investigation and an answer.

Best regards,
Sven
