### ISSUE TITLE
debug to msgbox broken

### ISSUE THREAD

**Issue by Huesdon** [loganch/AutoIt-VSCode#4]
Throws error about needing to select a variable or macro to generate but it doesn't matter what I highlight. Ideally there would also be the option to debug to console (which beats the crap out of msgbox)

**Comment by loganch** [comment]
Right now I have the extension limit creating a debug MsgBox to when the selected text begins with a '$' or '@' (it will ignore whitespace before and after). As I said in the other issue, console output sounds great and I'm looking into getting it working.

**Comment by Huesdon** [comment]
Apologies for the multiple issue posts, the prospect of a proper editor got
me excited.

**Comment by Huesdon** [comment]
Works as intended.
