### ISSUE TITLE
How do you run Tidy to format the code?

### ISSUE THREAD

**Issue by carloselectro** [loganch/AutoIt-VSCode#41]
Even if I put Tidy in the correct path, I cannot format the autoit code.
How do you get it to work?

**Comment by loganch** [comment]
Do you have any more details about what is happening when you try to run
Tidy?

**Comment by WefNET** [comment]
CTRL + ALT + P and find AutoIT: Tidy in the list.. There is no hotkey.

**Comment by carloselectro** [comment]
Thanks it's working now. My bad.
I have assigned a shortcut for it in vscode.

Thanks a lot for your help.

Le mer. 20 févr. 2019 22:57, John Wefler <notifications@github.com> a
écrit :

**Comment by loganch** [comment]
Thanks, @WefNET.
