### ISSUE TITLE
Why does debugging require Scite4AutoIt3?

### ISSUE THREAD

**Issue by mica** [loganch/AutoIt-VSCode#42]
Would it be possible to make this work with only the base install of AutoIt?

**Comment by loganch** [comment]
The full install of Scite4AutoIt3 has good tools written in AutoIt that are
easy to link to and run from the extension. On the main forum, the
maintainer expressed wishes that they not be separated to integrate into
the extension, so I just set that as a requirement and focused on getting
cool IDE features working.

**Comment by mica** [comment]
Ok, good to know 👍
