### ISSUE TITLE
AutoIt Help launching but not displaying context-sensitive help

### ISSUE THREAD

**Issue by RooseBaker** [loganch/AutoIt-VSCode#44]
Context-sensitive help is not displayed when an AutoIt function has focus or is selected
What am I missing?

VSCode x64 1.32.3 portable
AutoIt3 x64 3.3.14.5 portable

**Comment by loganch** [comment]
@RooseBaker My apologies for the really late response, but are you talking about Ctrl+F1 to launch the documentation in the AutoIt Help File?

If that is the issue, have you updated the paths in the configuration to match the location of your portable install of AutoIt?

**Comment by RooseBaker** [comment]
AutoIt help launches, but it doesn't show context-sensitive help for the AutoIt function near (or selected) the cursor

**Comment by loganch** [comment]
Hmmm... Do you have your portable set up on a drive other than the C: drive? And is the help blank when it launches?

**Comment by RooseBaker** [comment]
Yes, portable setup is on H:
 
"autoit.aiPath": "H:\\Portable\\AutoIt3P\\AutoIt3.exe",
    "autoit.checkPath": "H:\\Portable\\AutoIt3P\\AU3Check.exe",
    "autoit.consoleParams": "",
    "autoit.helpPath": "H:\\Portable\\AutoIt3P\\AutoIt3Help.exe",
    "autoit.includePaths": [
        "H:\\Portable\\AutoIt3P\\Include"
    ],
    "autoit.infoPath": "H:\\Bin\\Open-Au3Info.exe",
    "autoit.kodaPath": "H:\\Portable\\AutoIt3P\\SciTE\\Koda\\FD.exe",
    "autoit.showVariablesInGoToSymbol": true,
    "autoit.tidyPath": "H:\\Portable\\AutoIt3P\\SciTE\\Tidy\\Tidy.exe",
    "autoit.wrapperPath":
"H:\\Portable\\AutoIt3P\\SciTE\\AutoIt3Wrapper\\AutoIt3Wrapper.au3",
 

 
Help launches, but not on the command selected, or under the cursor
 
  _____

**Comment by loganch** [comment]
Does the help file show anything in the right pane?
