### ISSUE TITLE
Uncomplete "Go to definition" (issue #39)

### ISSUE THREAD

**Issue by Sven-Seyfert** [loganch/AutoIt-VSCode#46]
**Hi and sorry Logan**,

your fix in file `src\ai_definition.js` for adding "Go to definition" seems to be uncomplete. It works for definitions **in the same file** which is the usage of the function. But when I have the definiton in a separate file which is also located in the workspace and on the same level, I can not do the "jump" to that file.

It doesn't work unfortunatly.

---

I really tried to do it on my own and set a pull request then, but I couldn't achieve the correct result.
I tried to combine code of `src\ai_definition.js` and `src\ai_workspaceSymbols.js` to iterate through all files, but I loosed.

If you need more information, please let me know.
Thanks for your investigation and an answer.

Best regards,
Sven

**Comment by loganch** [comment]
Hi @Sven-Seyfert,
I think I've been able to figure how to get it working. Currently I have it just getting includes from user scripts. I'm thinking of also enabling the lookup for definition within the UDF files.

**Comment by Sven-Seyfert** [comment]
**Hi Logan**,

would be awesome if you could complete it with the UDF includes - I'm very grateful for that!
I already was looking into your code changes, good work and understandable (nice).

Best regards,
Sven

**Comment by loganch** [comment]
Hello Sven-Seyfert, let me know if the new v1.0.0 works for you
