### ISSUE TITLE
Newbie Help?

### ISSUE THREAD

**Issue by NikolaosB** [loganch/AutoIt-VSCode#47]
I have the latest VS Code, AutoIt-VSCode extension and AutoIt with SciTE 4.1.2. script editor installed. Loaded a script in VS Code. Clicked "Debug|Start Debugging" in VS Code...."Select Environment" appears. I've no idea what it wants.

How do I use this product?

Thanks,

Neal

**Comment by loganch** [comment]
Hello, @NikolaosB, unfortunately we don’t have direct debug functionality built for AutoIt in the same way that JavaScript and Python have it. 

You can run the scripts from VSCode and view console output that’s been set with ConsoleWrite(), but peering into variables as they change and setting breakpoints isn’t even available in SciTe.

**Comment by NikolaosB** [comment]
- Understood. I noticed that running (F5) in VS Code appears to work fine. Thank you for that. 
- Although watching variables isn't supported, do you know if Stepping Through lines of code in VS Code supported?  It doesn't appear to be.

Thank you again.

**Comment by loganch** [comment]
Sorry, stepping through lines is not supported.
