### ISSUE TITLE
No intellisense & description for _DebugArrayDisplay of Debug.au3

### ISSUE THREAD

**Issue by mrcancer91** [loganch/AutoIt-VSCode#48]
Hello Loganch, 
I really enjoy your plugin for AutoIT in VSC. However, I don't see the IntelliSense works with the _DebugArrayDisplay function (defined in Debug.au3). 
I use this function a lot so it would be nice if this can be fixed in the next release. 

Thanks & best regards,

**Comment by loganch** [comment]
Hi @mrcancer91, thanks for bringing this to my attention. I took a look at the documentation and it looks a few of the things I have in place for Debug.au3 are out of date.

**Comment by mrcancer91** [comment]
@loganch Could I continue to report small syntax highlight bugs/issues in this topic to avoid create many issues that have similar content? 
If yes, the below are syntax highlight issue for Keyboards in Send function, currently they're all treated as String: 

```AutoIT
"{ALTDOWN}, {ALTUP}, {CTRLDOWN}, {CTRLUP}, {LWINDOWN}, {LWINUP}, {RWINDOWN}, {RWINUP}, {SHIFTDOWN}, {SHIFTUP}"
```
Like the below image, it should be highlighted as `{ESC}` key
![image](https://user-images.githubusercontent.com/4757156/66977548-9ed2f500-f0d0-11e9-8b5b-a286ffbc1c72.png)

**Comment by loganch** [comment]
@mrcancer91 I just got `_DebugDisplayArray()` added into the extension. I would prefer you place issues separately, but I'll look into this syntax highlighting problem. Thanks again!

**Comment by mrcancer91** [comment]
Hi @loganch , 
I already saw your fixes for `{*DOWN}` but haven't got the syntax highlighting for `{*UP}`. 
Did you intentionally leave syntax like this?
![image](https://user-images.githubusercontent.com/4757156/67541398-0281a180-f713-11e9-998c-114db1f45536.png)

**Comment by loganch** [comment]
Ah, I made sure I included everything from the 1st column of the [SendKeys Documentation](https://www.autoitscript.com/autoit3/docs/appendix/SendKeys.htm), but looks like the *UP variants are in the comments in the 2nd column, my mistake.

**Comment by mrcancer91** [comment]
The description appeard as expected. Thank you @loganch
