### ISSUE TITLE
Code completion issue for user-defined functions

### ISSUE THREAD

**Issue by mrcancer91** [loganch/AutoIt-VSCode#52]
Hi Loganch,

I'm so happy to know that version 1.0.2 is released.
But I found a weird behavior with code completion, for user-defined functions.
For example, I have a function named `_LogDbg`. In previous version (`1.0.1`, to be exact), when I type `_Logdbg` then a hint would show up like below
![image](https://user-images.githubusercontent.com/4757156/69132460-b6920480-0ae6-11ea-8918-936587775f70.png)

But in version `1.0.2`, the hint shows like this
![image](https://user-images.githubusercontent.com/4757156/69132335-73379600-0ae6-11ea-93b8-d6a22b7502e1.png)
When selecting the function, I need to delete the `Func` by myself. And I feel a little uncomfortable. 
Is this intentionally made or just a bug?

Thank you!

**Comment by loganch** [comment]
Yeah I was getting that issue all today, too, looking into it...

**Comment by loganch** [comment]
Fixed in v1.0.3
