### ISSUE TITLE
Compiling doesn't take the current file

### ISSUE THREAD

**Issue by schulle877** [loganch/AutoIt-VSCode#53]
I like to compile the current au3-file. By pressing F7 I have to select the file to compile. I thought it might take the current file I just work on. Did I miss something?

**Comment by loganch** [comment]
Hmm, that is odd, F7 runs the build command would should just run
AutoIt3Wrapper and create an basic exe in the same directory without any
directives placed in it. Do you have any screenshots of the file selection
that it asks for?

**Comment by schulle877** [comment]
Well, I just found out I haven't installed Scite correctly. I didn't configure the wrapper-script. After installing Scite, configuring and restarting VSC it works perfectly. Thanks for that hint with the AutoIt3Wrapper.

**Comment by loganch** [comment]
I'm glad you found the solution!
