### ISSUE TITLE
Func keyword dectection has bug

### ISSUE THREAD

**Issue by mrcancer91** [loganch/AutoIt-VSCode#54]
Hi @loganch ,
I faced some error displaying function name in outline pallete. A stricter keyword parsing would fix this issue, I think. 
The image below could fully describe what I mean: 
![image](https://user-images.githubusercontent.com/4757156/71153720-72705c00-226c-11ea-8775-f5d48cb5a4ca.png)

By the way, could you please help to implement folding for `#Region - #EndRegion ` keywords?
Thank you!

**Comment by loganch** [comment]
Thanks for pointing these out!

**Comment by BB-19** [comment]
> 
> 
> Thanks for pointing these out!

Hi, the last update made the function detection worse than it was before.
Most functions are completely missing in big scripts.
I am using the old version for now which is working fine.

**Comment by loganch** [comment]
> > Thanks for pointing these out!
> 
> Hi, the last update made the function detection worse than it was before.
> Most functions are completely missing in big scripts.
> I am using the old version for now which is working fine.

Hi @BB-19, do you have screenshots/example code you can share to help me pinpoint the problem?

**Comment by BB-19** [comment]
Yeah, it looks like region indentation is causing the problem. Tidy has an option to indent regions.

Example code:
![region](https://user-images.githubusercontent.com/57269406/76266695-95f1e400-6268-11ea-87d9-4c0428969d66.PNG)

**Comment by loganch** [comment]
1.0.5 release addresses this.
