### ISSUE TITLE
How to locate error lines quickly

### ISSUE THREAD

**Issue by HaiDin-Peng** [loganch/AutoIt-VSCode#55]
Hi，loganch
I would like to know if there is any wrong positioning, which line will check for wrong click positioning or wavy line reminder
![error](https://user-images.githubusercontent.com/62110214/76539948-6fc48200-64bc-11ea-81cb-414b1f4a6fb6.PNG)

**Comment by loganch** [comment]
I think you're asking if it's possible to get Syntax checker warnings in the code, right?

**Comment by HaiDin-Peng** [comment]
Yes, thank you very much for your reply. I lack of English expression. I want to get the same error reminder function as AutoIT, so that I can jump to the wrong line quickly. I've tried to look at your source code and other language error reminders, but nothing.
Autoit Error reminding：
![ErrorTip](https://user-images.githubusercontent.com/62110214/76631458-b5488400-657c-11ea-819b-38fa6542cca6.PNG)
Others Language Error reminding:
![RedLine](https://user-images.githubusercontent.com/62110214/76631477-b974a180-657c-11ea-87c9-169a1a0a8cc6.PNG)

**Comment by loganch** [comment]
I'd like to get that working as well, it'll take some time for me to wrap my head around the API and the different checks to get it working.

**Comment by loganch** [comment]
I think you might like what you find in v1.0.6.
