### ISSUE TITLE
Syntax color constants

### ISSUE THREAD

**Issue by yann83** [loganch/AutoIt-VSCode#57]
Hello,

Is it possible to change constants color like @computername , in green for example for better code reading ?

Thank you for your work

**Comment by loganch** [comment]
Hi @yann83, coloring for macro constants like @ComputerName is controlled by your chosen Color Theme. You may be able to set them to a color you prefer by following the instructions in at [this link](https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme). I have them set as `constant.other.autoit` in the tmLanguage file.

**Comment by yann83** [comment]
Thank you for your help.
I've done this in \AppData\Roaming\Code\User\settings.json

`"editor.tokenColorCustomizations": {
        "textMateRules" : [
            {
                "scope": "constant.other.autoit",
                "settings": {
                    "foreground": "#3ab471"
                }
            }
        ]
    }`

**Comment by loganch** [comment]
I'm glad you got it working!
