### ISSUE TITLE
"Not" keyword not highlighted

### ISSUE THREAD

**Issue by dantronik-markus** [loganch/AutoIt-VSCode#69]
The "Not" keyword is not highlighted in purple in the following snippet:
```autoit
        If Not $windowPresent Then
            Local $excelDevWindowExists = WinExists("[CLASS:wndclass_desked_gsk]")
            If $excelDevWindowExists Then
                WinActivate("[CLASS:wndclass_desked_gsk]")
                Send("{F5}")
                $windowPresent = WinExists("[CLASS:#32770; TITLE:Microsoft Visual Basic]")
            EndIf
        EndIf
```

**Comment by Sven-Seyfert** [comment]
Hi @dantronik-markus ,

I think this depends on your VSCode theme. I use "One Dark Pro" and it looks like expected for your provided code snippet 😉 .

![grafik](https://user-images.githubusercontent.com/29656921/151796040-3e93c8e3-5ad9-4032-bcc9-93e3e44969c7.png)

Best regards
Sven

**Comment by dantronik-markus** [comment]
You're right! I use Dark+ (default design). I should probably report this to the VSCode developers, I assume?
