### ISSUE TITLE
Question about upcoming release

### ISSUE THREAD

**Issue by Sven-Seyfert** [loganch/AutoIt-VSCode#70]
Hi @loganch ,

I don't want to bother you at all and I appreciate your work on that VSCode extension 👍 .

**Anyway, one little question:**
When do you plan to publish a new Release?
I had a look on the current [diff](https://github.com/loganch/AutoIt-VSCode/compare/v1.0.6...HEAD) between the last release and the HEAD and I think it's worthy to release a new one or do you wait for a specific thing?

Best regards
Sven

**Comment by loganch** [comment]
Hey @Sven-Seyfert, I just uploaded the latest release!

https://github.com/loganch/AutoIt-VSCode/releases/tag/v1.0.7
