### ISSUE TITLE
Trouble with script output to console (again)

### ISSUE THREAD

**Issue by Huesdon** [loganch/AutoIt-VSCode#8]
Hey Logan,

So I fell into a looping BSOD and had to reset my system and consequently rebuild my dev environment. I have one issue remaining and that is the running script output to console with VSCode. I do not believe it is  your plugin but I am hoping you can offer a suggestion on how to track down the issue. 

Having zero output makes me want to go all "fight club" on my self.

**Comment by Huesdon** [comment]
Found it, VS Code needed to be run as admin.

**Comment by loganch** [comment]
Glad you were able to find the cause.
