### ISSUE TITLE
Hardcoded executable paths 

### ISSUE THREAD

**Issue by uberhalit** [loganch/AutoIt-VSCode#9]
Currently all executable paths are hardcoded inside [ai_commands.js](https://github.com/loganch/AutoIt-VSCode/blob/master/out/src/ai_commands.js#L6). Users that do not have AI installed (to that exact path) cannot use any of the advanced feature like running/building etc.

For example, I am not allowed to install anything that hasn't been approved by our sysadmin, however I can run portables (from non-system paths) just fine.

To work around this I had to manually alter the paths in `C:\Users\*user*\.vscode\extensions\Damien.autoit-0.1.2\out\src\ai_commands.js` and reload VSCode. Obviously this will be gone after an update.

Would be nice to have access to these path-variables via the ordinary VSCode `setting.json` which can be altered directly inside VSCode (File > Preferences > Settings): https://code.visualstudio.com/docs/getstarted/settings

For example [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner#configuration) has customizable paths for autoit.

**Comment by RonildoSouza** [comment]
#10

**Comment by RonildoSouza** [comment]
https://github.com/loganch/AutoIt-VSCode/releases/tag/v0.1.3
